updated to 4.15.0
Heyzap/facebook-audience-network-ane pull request #2
Opened 2016-09-07 15:17 UTC by sadensmol

2016-09-26 21:01 UTC, ekilah commented on build.config
> +air.sdk = /Applications/Adobe/air22_flex46
this file should be removed

2016-09-26 21:02 UTC, ekilah requested changes
im still having the weird issue we discussed on slack after updating my local setup to air 23...

2016-09-29 15:03 UTC, sadensmol commented
@ekilah removed file from the repo.. going to test with air23

2016-09-30 06:17 UTC, sadensmol commented
@ekilah tested with air23 and had the same error. I guess air23 is still in beta and FAN wasn't tested with it. Let's wait release of air23.

2022-05-17 06:28 UTC, closed without merging